# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-15 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrydate', models.DateField(default=datetime.date)),
                ('expirydate', models.DateField()),
                ('ctype', models.CharField(max_length=10)),
                ('customerid', models.CharField(max_length=50)),
                ('customername', models.CharField(max_length=50)),
                ('services', models.TextField()),
                ('worksummary', models.TextField()),
                ('details', models.TextField()),
                ('expectedresults', models.TextField()),
                ('estimatedhours', models.IntegerField()),
                ('hourlyrate', models.FloatField()),
                ('totalestimate', models.FloatField()),
                ('deposit', models.FloatField()),
                ('approved', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('rejected', models.BooleanField()),
                ('issigned', models.BooleanField()),
                ('depositpd', models.BooleanField()),
                ('dateupdated', models.DateField()),
                ('accepted', models.BooleanField()),
                ('dateaccepted', models.DateField()),
                ('completed', models.BooleanField()),
                ('datecompleted', models.DateField()),
                ('systemid', models.CharField(max_length=20)),
                ('PSCtype', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('introduction', models.TextField()),
                ('terms', models.TextField()),
                ('jobcompletion', models.TextField()),
                ('cancellation', models.TextField()),
                ('maintenance', models.TextField()),
                ('closing', models.TextField()),
                ('attachment', models.TextField()),
                ('websubid', models.CharField(max_length=20)),
                ('jobno', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('scheduledtime', models.TextField()),
                ('scheduleddtimechanges', models.TextField()),
                ('travelcosts', models.TextField()),
                ('timezone', models.CharField(max_length=40)),
                ('invoicenumbers', models.CharField(max_length=50)),
                ('maillingaddress', models.TextField()),
                ('limitofliability', models.TextField()),
                ('startwork', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('categeory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('Tenantid', models.AutoField(primary_key=True, serialize=False)),
                ('TenantName', models.CharField(max_length=50)),
            ],
        ),
    ]
