# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('status', models.CharField(choices=[('0', 'inactive'), ('1', 'active')], default='1', max_length=1)),
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('mobile_no', models.CharField(max_length=13, null=True)),
                ('remarks', models.TextField(null=True)),
                ('ismanager', models.BooleanField(default=False)),
                ('profilepic', models.ImageField(null=True, upload_to='images/')),
                ('createdOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('createdBy', models.CharField(max_length=50, null=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True, null=True)),
                ('modifiedBy', models.CharField(max_length=50, null=True)),
                ('recVersion', models.IntegerField(default=1, null=True)),
                ('first_name', models.CharField(default='', max_length=15)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('entrydate', models.DateField(default=datetime.date)),
                ('expirydate', models.DateField()),
                ('contractNumber', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ctype', models.CharField(max_length=10)),
                ('customerid', models.CharField(max_length=50)),
                ('customername', models.CharField(max_length=50)),
                ('services', models.TextField()),
                ('worksummary', models.TextField()),
                ('details', models.TextField()),
                ('expectedresults', models.TextField()),
                ('estimatedhours', models.IntegerField()),
                ('hourlyrate', models.FloatField()),
                ('totalestimate', models.FloatField()),
                ('deposit', models.FloatField()),
                ('approved', models.BooleanField()),
                ('verified', models.BooleanField()),
                ('rejected', models.BooleanField()),
                ('issigned', models.BooleanField()),
                ('depositpd', models.BooleanField()),
                ('dateupdated', models.DateField()),
                ('accepted', models.BooleanField()),
                ('dateaccepted', models.DateField()),
                ('completed', models.BooleanField()),
                ('datecompleted', models.DateField()),
                ('systemid', models.CharField(max_length=20)),
                ('PSCtype', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('introduction', models.TextField()),
                ('terms', models.TextField()),
                ('jobcompletion', models.TextField()),
                ('cancellation', models.TextField()),
                ('maintenance', models.TextField()),
                ('closing', models.TextField()),
                ('attachment', models.TextField()),
                ('websubid', models.CharField(max_length=20)),
                ('jobno', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('scheduledtime', models.TextField()),
                ('scheduleddtimechanges', models.TextField()),
                ('travelcosts', models.TextField()),
                ('timezone', models.CharField(max_length=40)),
                ('invoicenumbers', models.CharField(max_length=50)),
                ('maillingaddress', models.TextField()),
                ('limitofliability', models.TextField()),
                ('startwork', models.BooleanField()),
                ('expired', models.BooleanField()),
                ('categeory', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_Name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Tenant',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='tenantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractapp.Tenant'),
        ),
        migrations.AddField(
            model_name='contracts',
            name='tenantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractapp.Tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contractapp.Tenant'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
