# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 10:50
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0002_auto_20170518_1047'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
