# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0003_auto_20170518_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tenantid',
        ),
    ]
