# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0006_auto_20170518_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
