# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0007_auto_20170518_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='tenantid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contractapp.Tenant'),
            preserve_default=False,
        ),
    ]
