# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0009_auto_20170520_0542'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
            ],
        ),
    ]
