# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 10:58
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0010_auto_20170520_0616'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
