# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0011_auto_20170520_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='tenantid',
        ),
    ]
