# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractapp', '0013_auto_20170522_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
